name = "DepotDelivery"
uuid = "5c353f05-31b8-41b6-b09f-65e5456b8b1e"
authors = ["Josh Day <emailjoshday@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
Malt = "36869731-bdee-424d-aa32-cab38c994e3b"

[compat]
Malt = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
